# Generated by Django 4.2.2 on 2023-06-20 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=50, verbose_name='Imię')),
                ('lastname', models.CharField(blank=True, max_length=50, verbose_name='Nazwisko')),
                ('email', models.EmailField(blank=True, max_length=50, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Adres')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='Miasto')),
                ('country', models.CharField(blank=True, max_length=250, verbose_name='Kraj')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Data urodzenia')),
            ],
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(default='8254029236', max_length=10, unique=True, verbose_name='Numer karty')),
                ('expiration_date', models.DateField(default=datetime.datetime(2028, 6, 18, 9, 56, 58, 496527), verbose_name='Data ważności')),
                ('cvc_number', models.CharField(default='499', max_length=3, verbose_name='Numer CVC')),
                ('payment_amount', models.IntegerField(default=0.0, verbose_name='Kwota transakcji')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Data transakcji')),
                ('payments_counter', models.IntegerField(default=0, verbose_name='Licznik transakcji')),
                ('pin_number', models.CharField(default='2016', max_length=4, verbose_name='Kod PIN')),
            ],
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='8990407950', max_length=10, unique=True, verbose_name='Numer konta')),
                ('password', models.CharField(blank=True, default='67122', max_length=5, verbose_name='Hasło')),
                ('balance', models.IntegerField(verbose_name='Stan konta')),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccount.accountownermodel')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankaccount.creditcardmodel')),
            ],
        ),
    ]
