# Generated by Django 4.2.2 on 2023-06-20 11:23

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bankaccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountownermodel',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='accountownermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='password',
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='password',
            field=models.CharField(blank=True, max_length=5, verbose_name='Hasło'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='accountownermodel',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='Nazwa użytkownika'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='account_number',
            field=models.CharField(default='5659816781', max_length=10, unique=True, verbose_name='Numer konta'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='card_number',
            field=models.CharField(default='8601065053', max_length=10, unique=True, verbose_name='Numer karty'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='cvc_number',
            field=models.CharField(default='963', max_length=3, verbose_name='Numer CVC'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 6, 18, 11, 23, 14, 201147), verbose_name='Data ważności'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='pin_number',
            field=models.CharField(default='6264', max_length=4, verbose_name='Kod PIN'),
        ),
    ]
