# Generated by Django 4.2.2 on 2023-06-21 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0002_alter_accountownermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_firstname', models.CharField(max_length=50)),
                ('sender_lastname', models.CharField(max_length=50)),
                ('sender_account_number', models.CharField(max_length=10)),
                ('receiver_firstname', models.CharField(max_length=50)),
                ('receiver_lastname', models.CharField(max_length=50)),
                ('receiver_account_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='transaction_counter',
            field=models.IntegerField(default=0, verbose_name='Licznik transakcji'),
        ),
        migrations.AddField(
            model_name='creditcardmodel',
            name='transaction_counter',
            field=models.IntegerField(default=0, verbose_name='Licznik transakcji'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='account_number',
            field=models.CharField(default='3082740155', max_length=10, unique=True, verbose_name='Numer konta'),
        ),
        migrations.AlterField(
            model_name='accountownermodel',
            name='password',
            field=models.CharField(blank=True, max_length=8, verbose_name='Hasło'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='card_number',
            field=models.CharField(default='6802345546', max_length=10, unique=True, verbose_name='Numer karty'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='cvc_number',
            field=models.CharField(default='561', max_length=3, verbose_name='Numer CVC'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 6, 19, 16, 29, 52, 518418), verbose_name='Data ważności'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='pin_number',
            field=models.CharField(default='9667', max_length=4, verbose_name='Kod PIN'),
        ),
    ]
