# Generated by Django 4.2.2 on 2023-06-21 17:48

import bankaccount.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0003_transactionhistory_accountmodel_transaction_counter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='account_number',
            field=models.CharField(default='0364622434', max_length=10, unique=True, verbose_name='Numer konta'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='card_number',
            field=models.CharField(default=bankaccount.models.BaseModel.generate_uuid_nr, max_length=10, unique=True, verbose_name='Numer karty'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='cvc_number',
            field=models.CharField(default='758', max_length=3, verbose_name='Numer CVC'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 6, 19, 17, 48, 3, 565215), verbose_name='Data ważności'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='pin_number',
            field=models.CharField(default='1906', max_length=4, verbose_name='Kod PIN'),
        ),
    ]
