# Generated by Django 4.2.2 on 2023-06-21 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0006_alter_accountmodel_account_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionHistory',
            new_name='TransactionHistoryModel',
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='account_number',
            field=models.CharField(default='9663290220', max_length=10, unique=True, verbose_name='Numer konta'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='cvc_number',
            field=models.CharField(default='120', max_length=3, verbose_name='Numer CVC'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 6, 19, 18, 16, 21, 242052), verbose_name='Data ważności'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='pin_number',
            field=models.CharField(default='4096', max_length=4, verbose_name='Kod PIN'),
        ),
    ]
