# Generated by Django 4.2.2 on 2023-06-22 08:20

import bankaccount.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0007_rename_transactionhistory_transactionhistorymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='account_number',
            field=models.CharField(default=bankaccount.models.BaseModel.generate_account_number, max_length=10, unique=True, verbose_name='Numer konta'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='cvc_number',
            field=models.CharField(default='092', max_length=3, verbose_name='Numer CVC'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 6, 20, 8, 20, 1, 479316), verbose_name='Data ważności'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='pin_number',
            field=models.CharField(default='3012', max_length=4, verbose_name='Kod PIN'),
        ),
    ]
