# Generated by Django 4.2.2 on 2023-06-22 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccount', '0008_alter_accountmodel_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardmodel',
            name='cvc_number',
            field=models.CharField(default='793', max_length=3, verbose_name='Numer CVC'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2028, 6, 20, 9, 16, 6, 529639), verbose_name='Data ważności'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Kwota transakcji'),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='pin_number',
            field=models.CharField(default='9583', max_length=4, verbose_name='Kod PIN'),
        ),
    ]
